config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#home'
  get 'myprofile', to: 'lists#profile', as: :myprofile
  put 'lists/:id/like', to: 'lists#like', as: :list_like
  put 'movies/:id/like', to: 'movies#like', as: :movie_like
  resources :movies, only: [:index, :show] do
    resources :movie_reviews
  end
  resources :lists do
    resources :bookmarks
    resources :list_comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  belongs_to :user

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :list_comments, dependent: :destroy
  has_many :list_likes, dependent: :destroy

  belongs_to :user

  # cloudinary photo
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true

  def liked?(user)
    !!self.list_likes.find{|like| like.user_id == user.id }
  end
end

app/models/list_comment.rb
class ListComment < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/list_like.rb
class ListLike < ApplicationRecord
  belongs_to :list
  belongs_to :user
  validates :user_id, uniqueness: { scope: :list_id}
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :movie_reviews, dependent: :destroy
  has_many :movie_likes, dependent: :destroy

  validates :title, presence: true
  validates :overview, presence: true
  validates :rating, presence: true
  validates :poster_url, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title, 
    against: [:title],
    using: {
      tsearch: { prefix: true }
    }

  def liked?(user)
    !!self.movie_likes.find{|like| like.user_id == user.id }
  end
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: { scope: :movie_id } 
end

app/models/movie_review.rb
class MovieReview < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :comment, presence: true, length: { minimum: 6 }
  validates :rating, presence: true, length: { in: 1..10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :lists
  has_many :list_comments
  has_many :list_likes
  has_many :movie_likes
  has_many :movie_reviews

  # cloudinary for avatar
  has_one_attached :photo

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :like, :rating, :movie_id)
  end
end

app/controllers/list_likes_controller.rb
class ListLikesController < ApplicationController
  def create
    @list_like = ListLike.create(list_like_params)
    @list = List.find(:list_id)
    @list_like.list = @list
    @list_like.save
  end

  private

  def list_like_params
    require.param(:list_like).permit(:user_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show]
  def home
    # order lists by list_likes 
    @popular_lists = List.includes(:list_likes).sort{|a, b| b.list_likes.size <=> a.list_likes.size}
    @list = List.new
    @movies = Movie.order(rating: :desc)
    @movie_reviews = MovieReview.order(created_at: :desc)
  end

  def profile
    @account = current_user
  end

  def like
    # grep a list
    @list = List.find(params[:id])
    # create like with user id and list id
    ListLike.create(user_id: current_user.id, list_id: @list.id )
    redirect_to list_path(@list)
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @list_comment = ListComment.new
  end

  def new
    @list = List.new
    @popular_lists = List.includes(:list_likes).sort{|a, b| b.list_likes.size <=> a.list_likes.size}
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end    
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, :photo)
  end
end

app/controllers/movie_likes_controller.rb
class MovieLikesController < ApplicationController
  def create
    @movie_like = ListLike.create(movie_like_params)
    @movie = Movie.find(:movie_id)
    @movie_like.list = @movie
    @movie_like.save
  end

  private

  def movie_like_params
    require.param(:movie_like).permit(:user_id, :movie_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @movies = Movie.search_by_title(params[:query])
    else
      @movies = Movie.all
      # get 6 random movies
      @new_movies = Movie.all.sample(6)
      @movie_reviews = MovieReview.all
      @crew_picks = Movie.all.sample(10)
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @movie_review = MovieReview.new
  end

  def like
    # grep a movie
    @movie = Movie.find(params[:id])
    # create like with user id and list id
    MovieLike.create(user_id: current_user.id, movie_id: @movie.id )
    redirect_to movie_path(@movie)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_comments_helper.rb
module ListCommentsHelper
end

app/helpers/list_likes_helper.rb
module ListLikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :rating, collection: 1..10 %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/edit.html.erb
<%= render 'form', list: @list, bookmark: @bookmark %>

app/views/bookmarks/new.html.erb
<%= render 'form', list: @list, bookmark: @bookmark %>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/lists/_ux_card.html.erb
<div class="ux-cards">
  <h1> WATCH:LIST Lets You...</h1>
  <div class="ux-cards__top d-flex">
    <div class="ux-card">
      <p>You will have this and this</p>
    </div>
    <div class="ux-card">
      <p>You will have this and this</p>
    </div>
  </div>
  <div class="ux-cards__bottom d-flex">
    <div class="ux-card">
      <p>You will have this and this</p>
    </div>
    <div class="ux-card">
      <p>You will have this and this</p>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render 'form', list: @list %>

app/views/lists/home.html.erb
<div class="banner_big full-width">
  <div class="container">
    <h1>SHARE YOUR INSPIRATION AND BECOME A WATCH LISTER</h1>
    <p>show us your world behind the screen</p>
    <% if user_signed_in? %>
      <%= link_to "EXPLORE WATCH:LISTS", new_user_registration_path, class: "button_big" %>
    <% else %>
      <%= link_to "BECOME A WATCH:LISTER", new_user_registration_path, class: "button_big" %>
    <% end %>
  </div>
</div>

<%# user experiences %>
<%= render 'ux_card' %>

<div class="banner_middle">
  <h1>Now shut up and create a list</h1>
  <%= link_to "create list", new_list_path, class: "button_big" %>
</div>

<div class="popular_movies">
  <h4>POPULAR MOVIES</h4>
  <ul class="list-inline flex-between">
    <% @movies.take(6).each do |movie| %>
      <li>
        <a href="<%= movie_path(movie) %>">
          <%= image_tag movie.poster_url, class: "poster_middle" %>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<div class="row">

  <div class="list-card_middle col-8">
    <h4>JUST REVIEWED...</h4>
    <ul class="list-none">
      <% @movie_reviews.take(8).each do |review| %>
        <li class="d-flex">
          <div>
            <a href="<%= movie_path(review.movie) %>">
              <%= image_tag review.movie.poster_url, class: "poster_small" %>
            </a>
          </div>
          <div>
            <h1><%= review.movie.title %></h1>
            <h5>@<%= review.user.username %> / rating:<%= review.rating %></h5>
            <p><%= review.comment %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="popular-lists col-4">
    <h4>POPULAR LISTS THIS WEEK...</h4>
    <% @popular_lists.take(8).each do |list| %>
      <div class="list-card_small">
        <div>
          <h1><%= link_to list.name, list_path(list) %></h1>
          <p>@<%= list.user.username %> <%= list.list_likes.count %> like <%= list.list_comments.count %>comments</p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/lists/index.html.erb
<div class="lists">
  <div class="banner_middle">
    <h1>CREATE YOUR OWN WATCH:LIST</h1>
    <%= link_to "CREATE LIST", new_list_path, class: "button_big" %>
  </div>
</div>

<h4>POPULAR THIS WEEK...</h4>
<div class="popular_list">
  <div class="d-flex">
    <% @lists[0..1].each do |list| %>
      <div class="list-card_small">
        <div>
          <h1><%= link_to list.name, list_path(list) %></h1>
          <h4>@<%= list.user.username %> <%= list.list_likes.count %> like <%= list.list_comments.count %> comments</h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex">
    <% @lists[2..3].each do |list| %>
      <div class="list-card_small">
        <div>
          <h1><%= link_to list.name, list_path(list) %></h1>
          <h4>@<%= list.user.username %> <%= list.list_likes.count %> like <%= list.list_comments.count %> comments</h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<h4>RECENTLY LIKED...</h4>
<% @lists.each do |list| %>
  <div class="list-card_wide">
    <h4><%= link_to list.name, list_path(list) %></h4>
    <p>@<%= list.user.username %> <%= list.list_likes.count %> like <%= list.list_comments.count %> comments</p>
    <p><%= list.description %></p>
  </div>
<% end %>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

app/views/lists/profile.html.erb
email: <%= @account.email %>
username: <%= @account.username %>
<%= link_to "edit profile",  edit_user_registration_path %>

app/views/lists/show.html.erb
<div class="list-banner">
  <% if @list.photo.attached? %>
    <%= cl_image_tag @list.photo.key, height: 400, width: 400, crop: :fill %>
  <% else %>
    <%= image_tag "list.jpg" %>
  <% end %>
</div>

<p> <%= image_tag "avatar.jpg", class: "avatar-small" %> LISTED BY USERNAME</p>
<div class="list-title d-flex">
  <h1><%= @list.name %></h1>
  <p>
    <%= link_to "edit", edit_list_path(@list) %> / 
    <%= link_to "delete", 
        list_path,
        method: :delete,
        data: { confirm: "are you sure?" }
    %> / 
    <%= link_to "add a moive", new_list_bookmark_path(@list,@bookmark)%>
  </p>
</div>

<div class="row">
  <div class="list-info col-9">
    <h3><%= @list.description %></h3>
  </div>

  <ul class="list-info-card list-none col-3">
    <li><%= @list.movies.count %> MOVIES</li>
    <li><%= @list.list_likes.count %> LIKES</li>
    <li>SHARE</li>
  </ul>
</div>

<h1>LIKE BUTTON</h1>
<% if user_signed_in? %>
  <% if @list.liked?(current_user) %>
    <%= button_to "like", list_like_path(@list), method: :put, disabled: true %>
  <% else %>
    <%= button_to "like", list_like_path(@list), method: :put %>
  <% end %>
<% end %>


  <ul class="list-bookmarks list-inline">
    <% @list.bookmarks.each do |bookmark|  %>
      <li>
        <a href="<%= movie_path(bookmark.movie) %>">
          <%= image_tag bookmark.movie.poster_url, class: "poster_middle" %>
        </a>
        <p><%= bookmark.rating %> / 10</p>
        <p>
          <%= link_to "edit", edit_list_bookmark_path(@list, bookmark)%>
          <%= link_to "delete", 
              list_bookmark_path(@list, bookmark),
              method: :delete,
              data: { confirm: "are you sure?" }
          %>
        </p>
<% 
=begin %>
        click or mouse over modal
        <p><%= bookmark.comment %></p>
<% 
=end %>
      </li>
    <% end %>  
  </ul>

<div class="list_comments">
  <% @list.list_comments.each do |comment| %>
    <p>
      COMMENT BY USERNAME
      <%= link_to "edit", edit_list_list_comment_path(@list, comment) %>
      <%= link_to "delete", list_list_comment_path(@list, comment), method: :delete, data: { confirm: "are you sure?" } %>
    </p>
    <p><%= comment.comment %></p>
  <% end %>
  
  <div class="list_comment_form">
    <%= render 'list_comments/form', list: @list, list_comment: @list_comment %>
  </div>
</div>