config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#home'
  get 'myprofile', to: 'lists#profile', as: :myprofile
  put 'lists/:id/like', to: 'lists#like', as: :list_like
  put 'movies/:id/like', to: 'movies#like', as: :movie_like
  resources :movies, only: [:index, :show] do
    resources :movie_reviews
  end
  resources :lists do
    resources :bookmarks
    resources :list_comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  belongs_to :user

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :list_comments, dependent: :destroy
  has_many :list_likes, dependent: :destroy

  belongs_to :user

  # cloudinary photo
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true

  def liked?(user)
    !!self.list_likes.find{|like| like.user_id == user.id }
  end
end

app/models/list_comment.rb
class ListComment < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/list_like.rb
class ListLike < ApplicationRecord
  belongs_to :list
  belongs_to :user
  validates :user_id, uniqueness: { scope: :list_id}
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :movie_reviews, dependent: :destroy
  has_many :movie_likes, dependent: :destroy

  validates :title, presence: true
  validates :overview, presence: true
  validates :rating, presence: true
  validates :poster_url, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title, 
    against: [:title],
    using: {
      tsearch: { prefix: true }
    }

  def liked?(user)
    !!self.movie_likes.find{|like| like.user_id == user.id }
  end
end

app/models/movie_like.rb
class MovieLike < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: { scope: :movie_id } 
end

app/models/movie_review.rb
class MovieReview < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates :comment, presence: true, length: { minimum: 6 }
  validates :rating, presence: true, length: { in: 1..10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :lists
  has_many :list_comments
  has_many :list_likes
  has_many :movie_likes
  has_many :movie_reviews

  # cloudinary for avatar
  has_one_attached :photo

  validates :username, presence: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :like, :rating, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show]
  def home
    # order lists by list_likes 
    @popular_lists = List.includes(:list_likes).sort{|a, b| b.list_likes.size <=> a.list_likes.size}
    @list = List.new
    @movies = Movie.order(rating: :desc)
    @movie_reviews = MovieReview.order(created_at: :desc)
  end

  def profile
    @account = current_user
  end

  def like
    # grep a list
    @list = List.find(params[:id])
    # create like with user id and list id
    ListLike.create(user_id: current_user.id, list_id: @list.id )
    redirect_to list_path(@list)
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @list_comment = ListComment.new
  end

  def new
    @list = List.new
    @popular_lists = List.includes(:list_likes).sort{|a, b| b.list_likes.size <=> a.list_likes.size}
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end    
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @movies = Movie.search_by_title(params[:query])
    else
      @movies = Movie.all
      # get 6 random movies
      @new_movies = Movie.all.sample(6)
      @movie_reviews = MovieReview.all
      @crew_picks = Movie.all.sample(10)
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @movie_review = MovieReview.new
  end

  def like
    # grep a movie
    @movie = Movie.find(params[:id])
    # create like with user id and list id
    MovieLike.create(user_id: current_user.id, movie_id: @movie.id )
    redirect_to movie_path(@movie)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_comments_helper.rb
module ListCommentsHelper
end

app/helpers/list_likes_helper.rb
module ListLikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movie_likes_helper.rb
module MovieLikesHelper
end

app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_list_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-watchlist">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h3>WATCH:LIST</h3>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "MOVIES", movies_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "LISTS", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% else %>
              <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", myprofile_path, class: "dropdown-item" %>
              <%= link_to "Lists", '#', class: "dropdown-item" %>
              <%= link_to "Movies", '#', class: "dropdown-item" %>
              <%= link_to "Reviews", '#', class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "CREATE ACCOUNT", new_user_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "SIGN IN", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>